### ISSUE TITLE
Setup linting task

### ISSUE THREAD

**Issue by rowlandekemezie** [CoWare/Licit#36]
- [x] Use eslint
- [x]  Use jscsrc
- [x] [Add editorConfig rules](http://editorconfig.org/)

You would need to add this linting as a gulp task and include the script for it in our package.json

**Comment by rowlandekemezie** [comment]
I don't know what the update is on setting gulp task @demiladebamgbose @aezumezu

**Comment by cyrielo** [comment]
Can you explain the jscsrc more, how do i integrate that? I understand it is a set of predefined rules for code quality, how do i add it to the eslint config file?

**Comment by rowlandekemezie** [comment]
@cyrielo You're right. But since eslint has merged with jscs. We can leave that.
http://jscs.info/

**Comment by rowlandekemezie** [comment]
Remember to ask everybody to install editorConfig in their editor of use after your PR is merged.

**Comment by rowlandekemezie** [comment]
Can you respond to your issue. Just pull develop and you'd be fine
