### ISSUE TITLE
Setup Server side Folder structure

### ISSUE THREAD

**Issue by rowlandekemezie** [CoWare/Licit#38]
Take this an example. Do the best you can and submit your decisions with your PR

https://github.com/andela-rekemezie/Document-Manager-REST-API

**Comment by ghost** [comment]
@andela-rekemezie Do I just setup the empty folders, cause I've done that now

**Comment by rowlandekemezie** [comment]
Yep but it requires some basic express setup. In the meantime, API architecting session needs to happen

**Comment by ghost** [comment]
I added the app, config, seeds folder and a .env file. I also added controllers, middleware, routes and models folders as sub-folder in app
